#!/usr/bin/env python3
"""
Build a catalogue of every page: our engine's output against another engine's.

Both rasters come from poppler at the same DPI, so any difference is ours. Our side is
the document as *our* engine writes it (exported PDF); the reference is the original.
Findings are grouped into regions so the list is per-defect, not per-pixel.
"""
import base64
import json
import pathlib
import subprocess
import sys
import urllib.request

import numpy as np
from PIL import Image

ROOT = pathlib.Path(r"C:\Users\submu\vccad-win")
DPI = 150
WORK = ROOT / "artifacts" / "catalogue"
(WORK / "ours").mkdir(parents=True, exist_ok=True)
(WORK / "ref").mkdir(parents=True, exist_ok=True)


def invoke(op, params):
    body = json.dumps({"op": op, "params": params}).encode()
    request = urllib.request.Request(
        "http://127.0.0.1:5099/api/v1/invoke", data=body,
        headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(request, timeout=900) as response:
        return json.loads(response.read().decode())


def export_document():
    payload = invoke("document.exportPdf", {})
    data = payload["result"]["pdfBase64"] if "pdfBase64" in payload["result"] else payload["result"]
    path = WORK / "ours.pdf"
    path.write_bytes(base64.b64decode(data))
    return path


def rasterise(pdf, prefix):
    subprocess.run(
        ["wsl.exe", "bash", "-lc",
         f"cd /mnt/c/Users/submu/vccad-win && pdftoppm -r {DPI} -png "
         f"'{pdf.relative_to(ROOT).as_posix()}' 'artifacts/catalogue/{prefix}/p'"],
        check=True,
    )


def regions(diff, threshold=90, min_area=40):
    """Group strongly-different pixels into bounding boxes, coarsest first."""
    mask = diff.max(axis=2 if diff.ndim == 3 else 0) > threshold
    if mask.ndim == 3:
        mask = mask.max(axis=2)
    # Coarse grid clustering keeps this simple and good enough to name a region.
    h, w = mask.shape
    cell = 24
    hits = []
    for cy in range(0, h // cell):
        for cx in range(0, w // cell):
            block = mask[cy * cell:(cy + 1) * cell, cx * cell:(cx + 1) * cell]
            if block.sum() > min_area:
                hits.append((cx * cell, cy * cell, block.sum()))

    merged = []
    for x, y, count in sorted(hits, key=lambda t: -t[2]):
        for i, (mx, my, mw, mh, mc) in enumerate(merged):
            if abs(x - mx) < 120 and abs(y - my) < 120:
                merged[i] = (min(mx, x), min(my, y), max(mw, x), max(mh, y), mc + count)
                break
        else:
            merged.append((x, y, x, y, count))
    return sorted(merged, key=lambda t: -t[4])[:12]


def main():
    ours_pdf = export_document()
    rasterise(ours_pdf, "ours")
    rasterise(ROOT / "samples" / "3464_LILLIE_View_A_Sides_color.pdf", "ref")

    lines = [
        "# Rendering catalogue — 3464_LILLIE_View_A_Sides_color.pdf",
        "",
        f"Generated by `tools/fonts-compare/build_catalogue.py` at {DPI} dpi.",
        "",
        "Both sides are rasterised by poppler from the same DPI, so every difference below",
        "is produced by VCCad. **Ours** is our engine's exported output; **reference** is the",
        "original file.",
        "",
        "| page | RMSE | strongly-different px | worst region (px) |",
        "|---|---|---|---|",
    ]

    detail = []
    for index in range(1, 13):
        ref_path = WORK / "ref" / f"p-{index:02d}.png"
        our_path = WORK / "ours" / f"p-{index:02d}.png"
        if not ref_path.exists() or not our_path.exists():
            lines.append(f"| {index} | — | — | missing raster |")
            continue

        ref = Image.open(ref_path).convert("RGB")
        ours = Image.open(our_path).convert("RGB")
        if ref.size != ours.size:
            ours = ours.resize(ref.size, Image.LANCZOS)

        a = np.asarray(ref, dtype=np.int16)
        b = np.asarray(ours, dtype=np.int16)
        diff = np.abs(a - b)
        rmse = float(np.sqrt((diff.astype(np.float64) ** 2).mean()))
        bad = int((diff.max(axis=2) > 90).sum())
        found = regions(diff)

        worst = f"({found[0][0]},{found[0][1]})" if found else "—"
        lines.append(f"| {index} | {rmse:.1f} | {bad:,} | {worst} |")

        detail.append((index, rmse, bad, found))

    lines += ["", "## Per-page detail", ""]
    for index, rmse, bad, found in detail:
        lines.append(f"### Page {index} — RMSE {rmse:.1f}, {bad:,} differing pixels")
        lines.append("")
        if not found:
            lines.append("No region exceeded the threshold.")
        else:
            lines.append("| region (x, y) | approx size | differing px |")
            lines.append("|---|---|---|")
            for x, y, x2, y2, count in found:
                lines.append(f"| ({x}, {y}) | {max(x2-x,24)}x{max(y2-y,24)} | {count:,} |")
        lines.append("")

    # Provenance. A defect list with no date is worse than none: this file has already
    # sent one round chasing "no clipping operator" and "missing logo" months after both
    # were fixed, because nothing in it said which build produced it.
    import datetime
    import subprocess
    # The checkout that has a .git is the WSL one; this script runs against the Windows
    # mirror, which does not, so ask WSL for it.
    revision = "unknown"
    for attempt in (
        ["git", "-C", "/home/darren/development/vccad", "rev-parse", "--short", "HEAD"],
        ["git", "rev-parse", "--short", "HEAD"],
    ):
        try:
            command = attempt if attempt[0] == "git" and attempt[1] == "-C" else attempt
            if command[1:2] == ["-C"]:
                result = subprocess.run(["wsl", "-e"] + command, capture_output=True,
                                        text=True, timeout=15)
            else:
                result = subprocess.run(command, cwd=str(ROOT), capture_output=True,
                                        text=True, timeout=15)
            candidate = result.stdout.strip().splitlines()
            if candidate and candidate[0]:
                revision = candidate[0]
                break
        except Exception:
            continue

    stamp = [
        "",
        "---",
        "",
        f"Generated {datetime.datetime.now().isoformat(timespec='seconds')} "
        f"from revision `{revision}`.",
        "",
        "**Treat any finding here as describing that revision and no other.** Regenerate "
        "before acting on it.",
        "",
        "## Colour space",
        "",
        "The reference paints with **DeviceCMYK** exclusively (about 1,590 `k`/`K` "
        "operators, and 153 `SCN`), and declares no output intent.",
        "",
        "A viewer colour-manages DeviceCMYK rather than applying the naive "
        "`r = (1-c)(1-k)` the importer used to. Measured with `tools/fonts-compare/"
        "cmyk_probe.py`: `k=0.3` renders as 189/255 where the formula gives 178, `k=1` "
        "as (35,31,32) rather than black, and pure cyan as (0,173,239) rather than "
        "(0,255,255). Converting at import therefore loses something that cannot be "
        "recovered. The original ink values are now kept on the model and written back "
        "out, which improved every page.",
        "",
        "The same cause explains the grey page corners, which now match exactly, and most "
        "of what is left on the embedded raster - the largest differing region remaining.",
        "",
    ]
    lines += stamp

    out = WORK / "CATALOGUE.md"
    out.write_text("\n".join(lines), encoding="utf-8")

    print(f"wrote {out}")
    print("\n".join(lines[:20]))


if __name__ == "__main__":
    sys.exit(main())
